export const metadata = {
  title: 'Config',
  description: 'Generated by create next app',
};

export default async function ConfigLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex flex-row justify-center align-middle items-center h-screen ">
      {children}
    </div>
  );
}
