import './globals.css';
import { Inter } from 'next/font/google';
import LoadingProvider from '@/provider/loading.provider';
import { SessionProvider } from '@/provider/auth.provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'ChatGPT',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LoadingProvider>
          <SessionProvider>
            <div className="bg-[#e2e8f0] flex-1">{children}</div>
          </SessionProvider>
        </LoadingProvider>
      </body>
    </html>
  );
}
